import { atom } from "jotai";
import { drone } from "./interfaces";

const sampleData: drone[] = [
  {
    id: "1",
    name: "SkyRanger",
    description: "Advanced reconnaissance drone with high endurance.",
    type: "air",
    engineType: "electric",
    fuelOrBatteryLevel: 85,
    currentLatitude: 26.1231,
    currentLongitude: -118.2437,
    maxSpeedKmh: 120,
    maxDistanceKm: 500,
    pricePerHourUSD: 50,
    noiseLevelDb: 45,
    lengthCm: 100,
    widthCm: 80,
    heightCm: 30,
    maxLoadKg: 5,
    specialization: "reconnaissance",
    isActive: true,
    isOnMission: false,
  },
  {
    id: "2",
    name: "AquaDrone",
    description: "Water drone for marine research and rescue operations.",
    type: "water",
    engineType: "fuel",
    fuelOrBatteryLevel: 70,
    currentLatitude: 34.0522,
    currentLongitude: -218.2437,
    maxSpeedKmh: 60,
    maxDistanceKm: 300,
    pricePerHourUSD: 40,
    noiseLevelDb: 50,
    lengthCm: 150,
    widthCm: 100,
    heightCm: 40,
    maxLoadKg: 10,
    specialization: "rescue",
    isActive: true,
    isOnMission: false,
  },
  {
    id: "3",
    name: "TerraScout",
    description: "Land drone for agricultural monitoring and delivery.",
    type: "land",
    engineType: "electric",
    fuelOrBatteryLevel: 90,
    currentLatitude: 36.0522,
    currentLongitude: -118.2437,
    maxSpeedKmh: 40,
    maxDistanceKm: 200,
    pricePerHourUSD: 30,
    noiseLevelDb: 55,
    lengthCm: 120,
    widthCm: 90,
    heightCm: 50,
    maxLoadKg: 15,
    specialization: "agriculture",
    isActive: true,
    isOnMission: false,
  },
  {
    id: "4",
    name: "SpaceExplorer",
    description: "Drone designed for space exploration missions.",
    type: "space",
    engineType: "fuel",
    fuelOrBatteryLevel: 100,
    currentLatitude: 32,
    currentLongitude: 68,
    maxSpeedKmh: 15000,
    maxDistanceKm: 1000000,
    pricePerHourUSD: 1000,
    noiseLevelDb: 30,
    lengthCm: 200,
    widthCm: 150,
    heightCm: 100,
    maxLoadKg: 20,
    specialization: "reconnaissance",
    isActive: true,
    isOnMission: false,
  },
  {
    id: "5",
    name: "UrbanDrone",
    description: "Drone for urban delivery and logistics.",
    type: "air",
    engineType: "electric",
    fuelOrBatteryLevel: 80,
    currentLatitude: 50.34,
    currentLongitude: 22.03,
    maxSpeedKmh: 80,
    maxDistanceKm: 400,
    pricePerHourUSD: 60,
    noiseLevelDb: 40,
    lengthCm: 110,
    widthCm: 85,
    heightCm: 35,
    maxLoadKg: 8,
    specialization: "delivery",
    isActive: true,
    isOnMission: false,
  },
];

const dronesAtom = atom<drone[]>(sampleData);

export { dronesAtom };
